#! /usr/bin/env bash

pid=$$

cleanup(){
  rm -rf /tmp/ntpdrift.$pid
}

ctrl_c(){
  echo -e "\nCleaning up..."
  cleanup
  exit
}

trap ctrl_c SIGINT

while true
do 
  clear
  curtime=$(date +%s)
  offset=$(ntpq -c "rv 0 offset" | cut -d "=" -f 2) 
  echo -e "$curtime\t$offset" >> /tmp/ntpdrift.$pid
  gnuplot -e 'set terminal dumb; set ylabel "NTP Drift (ms)"; set xlabel "Time (in seconds since the epoch)"; plot "< tail -20 /tmp/ntpdrift.'"$pid"'" with lines;'
  sleep 60
done;
