#! /usr/bin/env bash

pid=$$
dest=google.com
dest=$1

cleanup(){
  rm -rf /tmp/ntpdrift.$pid
}

ctrl_c(){
  echo -e "\nCleaning up..."
  cleanup
  exit
}

while true
do
  ping -nc 1 $dest | grep time= | awk -F [=\ ] {'print $(NF-1)'} >> /tmp/pinggraph.$pid
  gnuplot -e 'set terminal dumb; set ylabel "Ping round trip time (ms)"; set xlabel "Number"; plot "< tail -20 /tmp/pinggraph.'"$pid"'" with lines;'
  sleep 0.25
done;
